# Generated by Django 4.2.20 on 2025-03-30 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(help_text='Informe o nome/identificação da sala', max_length=20, verbose_name='Nome da Sala')),
                ('quantidade_maxima', models.PositiveIntegerField(default=1, help_text='Quantidade máxima de pessoas permitida na sala', verbose_name='Capacidade Máxima')),
                ('status', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], default='PUBLIC', max_length=7)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unievangelica.bloco')),
            ],
        ),
    ]
