# Generated by Django 4.2.20 on 2025-03-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0002_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloco',
            options={'verbose_name': 'Bloco', 'verbose_name_plural': 'Blocos'},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
    ]
