# Generated by Django 4.2.20 on 2025-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0004_recursosala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='recursos_sala',
            field=models.ManyToManyField(to='unievangelica.recursosala', verbose_name='Nome do Recurso'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='nome_bloco',
            field=models.CharField(max_length=20, verbose_name='Nome do bloco'),
        ),
        migrations.AlterField(
            model_name='recursosala',
            name='nome_recurso',
            field=models.CharField(max_length=128, verbose_name='Nome do Recurso'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='status',
            field=models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada')], default='PUBLIC', help_text='Privada: Indica que essa sala é restrita para um curso<br>Pública: Indica que essa sala é liberada para qualquer curso.', max_length=7),
        ),
    ]
