# Generated by Django 4.2.20 on 2025-03-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0004_recursosala'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='recursos_sala',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unievangelica.recursosala'),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='nome_bloco',
            field=models.CharField(max_length=20, verbose_name='Nome do bloco'),
        ),
        migrations.AlterField(
            model_name='recursosala',
            name='nome_recurso',
            field=models.CharField(max_length=128, verbose_name='Nome do Recurso'),
        ),
    ]
