# Generated by Django 4.2.20 on 2025-04-01 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0006_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='curso',
            field=models.ForeignKey(help_text='Opcional, caso a sala seja pública.', null=True, on_delete=django.db.models.deletion.PROTECT, to='unievangelica.cursos', verbose_name='Curso associado:'),
        ),
    ]
