# Generated by Django 4.2.20 on 2025-04-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0008_alter_sala_curso_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='nome_reserva',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='reservas',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recorrencias', to='unievangelica.reservas'),
        ),
    ]
