# Generated by Django 4.2.20 on 2025-04-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unievangelica', '0009_reservas_nome_reserva_reservas_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='data_reserva',
            field=models.DateField(),
        ),
    ]
